[tool.poetry]
name = "pyramid-tutorial"
version = "0.1.0"
description = ""
authors = ["Pyramid Tutorial"]

[tool.poetry.dependencies]
python = "^3.8"
pyramid = "^1.10.4"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
waitress = "^1.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
